#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Early out for Bash <4.
if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
  echo "This build system requires Bash 4 or greater."
  exit
fi


#-------------------------------------------------------------------------------
# Get script directory
# http://stackoverflow.com/a/246128/404640
BC_SCRIPT_FILE="${BASH_SOURCE[0]}"
# resolve $BC_SCRIPT_FILE until the file is no longer a symlink
while [ -h "$BC_SCRIPT_FILE" ]; do
  BC_SCRIPT_DIR="$( cd -P "$( dirname "$BC_SCRIPT_FILE" )" && pwd )"
  BC_SCRIPT_FILE="$(readlink "$BC_SCRIPT_FILE")"
  # if $BC_SCRIPT_FILE was a relative symlink, we need to resolve it relative to
  # the path where the symlink file was located
  [[ $BC_SCRIPT_FILE != /* ]] && BC_SCRIPT_FILE="$BC_SCRIPT_DIR/$BC_SCRIPT_FILE"
done
BC_SCRIPT_DIR="$( cd -P "$( dirname "$BC_SCRIPT_FILE" )" && pwd )"
BC_SCRIPT_FILE=$(basename $BC_SCRIPT_FILE)


#-------------------------------------------------------------------------------
# top-level directories
BC_TOP_DIR="$BC_SCRIPT_DIR"
BC_LIB_DIR="$BC_TOP_DIR/lib"
#
BC_DEVTOOLS_DIR="$BC_TOP_DIR/devtools"
BC_PACKAGES_DIR="$BC_TOP_DIR/packages"
#
BC_SOURCE_DIR="$BC_TOP_DIR/sources"
BC_WORK_DIR="$BC_TOP_DIR/work"
BC_INSTALL_DIR="$BC_TOP_DIR/install"
BC_DIST_DIR="$BC_TOP_DIR/dist"

NODE_MODULES_BIN_DIR="$BC_TOP_DIR/node_modules/.bin"

mkdir -p "$BC_INSTALL_DIR"

#-------------------------------------------------------------------------------
# "purify" the PATH
PATH="$NODE_MODULES_BIN_DIR":"$BC_DEVTOOLS_DIR/bin":/usr/bin:/bin


#-------------------------------------------------------------------------------
. "${BC_LIB_DIR}/misc.sh"                 # global misc & helper functions
. "${BC_LIB_DIR}/toolchain.sh"            # Toolchain related setup
. "${BC_LIB_DIR}/help.sh" $BC_SCRIPT_FILE # Help, info, etc
. "${BC_LIB_DIR}/packages.sh"             # Package{s} info
. "${BC_LIB_DIR}/devenv.sh"               # build host specific package setup
. "${BC_LIB_DIR}/cli.sh"                  # build system cli opt processing
. "${BC_LIB_DIR}/stages.sh"               # build stages step encapsulation

#-------------------------------------------------------------------------------
bc_cli_process $@

#-------------------------------------------------------------------------------
# done
